ninety_nine_cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cats
  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post :approve
      post :deny
    end
  end

  root to: redirect('/cats')
end

ninety_nine_cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ninety_nine_cats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ApplicationRecord
  include ActionView::Helpers::DateHelper

  COLORS = ['brown', 'orange', 'grey', 'black', 'white']

  def self.cat_colors
    COLORS.map(&:capitalize)
  end

  validates :color, inclusion: COLORS
  validates :sex, inclusion: ['M', 'F']
  validates :name, :color, :sex, :birth_date, :description, presence: true

  def age
    time_ago_in_words(self.birth_date)
  end

  has_many :cat_rental_requests,
    foreign_key: :cat_id,
    class_name: :CatRentalRequest,
    dependent: :destroy
end

ninety_nine_cats/app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :bigint           not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("PENDING")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CatRentalRequest < ApplicationRecord
  validates :status, :inclusion => { :in => ['PENDING', 'APPROVED', 'DENIED'] }
  validates :cat_id, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true

  belongs_to :cat,
    foreign_key: :cat_id,
    class_name: :Cat

  def overlapping_requests
    CatRentalRequest
      .where.not(id: self.id)
      .where(cat_id: cat_id)
      .where.not('start_date > :end_date OR end_date < :start_date',
                 start_date: start_date, end_date: end_date)
  end

  def overlapping_approved_requests
    overlapping_requests.where('status = \'APPROVED\'')
  end

  def overlapping_pending_requests
    overlapping_requests.where('status = \'PENDING\'')
  end

  def does_not_overlap_approved_requests
    if !overlapping_approved_requests.empty?
      errors[:base] << 'This cat is not available on the selected dates.'
    end
  end

  def approve!
    ActiveRecord::Base.transaction do
      self.status = 'APPROVED'
      self.save!

      overlapping_requests.each do |rental_request|
        rental_request.deny!
      end
    end
  end

  def deny!
    self.status = 'DENIED'
    self.save!
  end

  def self.reset_requests!
      CatRentalRequest.all.each do |rental_request|
        rental_request.update!(status: 'PENDING')
      end
  end
end

ninety_nine_cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ninety_nine_cats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
    def new
        @cat_rental_request = CatRentalRequest.new

        render :new
    end

    def create
        @cat_rental_request = CatRentalRequest.new(cat_rental_request_params)

        if @cat_rental_request.save
            redirect_to cat_url(@cat_rental_request.cat)
        else
            render json: @cat_rental_request.errors.full_messages
        end
    end

    def approve
        @cat_rental_request = CatRentalRequest.find(params[:id])

        @cat_rental_request.approve!
        redirect_to cat_url(@cat_rental_request.cat)
    end

    def deny
        @cat_rental_request = CatRentalRequest.find(params[:id])
        
        @cat_rental_request.deny!
        redirect_to cat_url(@cat_rental_request.cat)
    end

    private

    def cat_rental_request_params
        params.require(:cat_rental_request).permit(:cat_id, :start_date, :end_date)
    end
end

ninety_nine_cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all

    render :index
  end

  def show
    @cat = Cat.find(params[:id])

    render :show
  end

  def new
    @cat = Cat.new

    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render json: @cat.errors.full_messages
    end
  end

  def edit
    @cat = Cat.find(params[:id])

    render :edit
  end

  def update
    @cat = Cat.find(params[:id])

    if @cat.update_attributes(cat_params)
      redirect_to cat_url(@cat)
    else
      render json: @cat.errors.full_messages
    end
  end

  private

  def cat_params 
    params.require(:cat).permit(:birth_date, :name, :color, :sex, :description)
  end
end

ninety_nine_cats/app/helpers/application_helper.rb
module ApplicationHelper
end

ninety_nine_cats/app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

ninety_nine_cats/app/helpers/cats_helper.rb
module CatsHelper
end

ninety_nine_cats/app/views/cat_rental_requests/new.html.erb
<h1>Make a Rental Request</h1>

<form action="<%= cat_rental_requests_url %>" method="post">
    <label for="cat">Cat
        <select name="cat_rental_request[cat_id]">
            <option disabled selected>-- Select a Cat --</option>
            <% Cat.all.each do |cat| %>
                <option value=<%= cat.id %>> <%= cat.name %> </option>
            <% end %>
        </select>
    </label>
    <br>
    <br>
    <label for="start_date">Start Date
        <input 
        type="date" 
        id="start_date" 
        name="cat_rental_request[start_date]" 
        value=<%= Time.now %>
        >
    </label>
    <br>
    <br>
    <label for="end_date">End Date
        <input 
        type="date" 
        id="end_date" 
        name="cat_rental_request[end_date]" 
        value=<%= Time.now + 7.days %>
        >
    </label>
    <br>
    <br>
    <input type="submit" value="Submit">
</form>

ninety_nine_cats/app/views/cats/_form.html.erb
  <% if type == :new %>
    <% action_url = cats_url %>
    <% button_text = 'Create Cat' %>
  <% elsif type == :edit %>
    <% action_url = cat_url(cat) %>
    <% button_text = 'Update Cat' %>
  <%end%>


<form action="<%= action_url %>" method="post">
  <% if type == :edit %>
    <input type="hidden" name="_method" value="patch">
  <%end%>
  <label for="name">Name
    <input type="text" id="name" name="cat[name]" value="<%= cat.name %>">
  </label>
  <br>
  <br>
  <label for="birth_date">Birth date
    <input type="date" id="birth_date" name="cat[birth_date]" value="<%= cat.birth_date %>">
  </label>
  <br>
  <br>
  <label for="color">Color
  <select name="cat[color]">
    <option disabled selected>-- Please Select --</option>
    <option value="brown" <%= cat.color == "brown" ? "selected" : "" %> > <%= Cat.cat_colors[0] %> </option>
    <option value="orange" <%= cat.color == "orange" ? "selected" : "" %> > <%= Cat.cat_colors[1] %> </option>
    <option value="grey" <%= cat.color == "grey" ? "selected" : "" %>> <%= Cat.cat_colors[2] %> </option>
    <option value="black" <%= cat.color == "black" ? "selected" : "" %> > <%= Cat.cat_colors[3] %> </option>
    <option value="white" <%= cat.color == "white" ? "selected" : "" %> > <%= Cat.cat_colors[4] %> </option>
  </select>
  </label>
  <br>
  <br>
  <label for="sex">Sex
    <input type="radio" id="sex" name="cat[sex]" value="M" <%= cat.sex == "M" ? "checked" : "" %> >Male
    <input type="radio" id="sex" name="cat[sex]" value="F" <%= cat.sex == "F" ? "checked" : "" %> >Female
  </label>
  <br>
  <br>
  <label for="description">Description
    <br>
    <textarea id="description" name="cat[description]" ><%= cat.description %></textarea>
  </label>
  <br>
  <br>
  <input type="submit" value=<%= button_text %>>
</form>

ninety_nine_cats/app/views/cats/edit.html.erb
<h1> Edit a Cat </h1>


<%= render 'form', cat: @cat, type: :edit %>

ninety_nine_cats/app/views/cats/index.html.erb
<h1> All Cats </h1>

<ul>
    <% @cats.each do |cat| %>
        <li> <%= cat.name  %> </li>
        <li> <a href="<%= cat_url(cat) %>"> Cat Details</a> </li>
    <% end %>
</ul>

ninety_nine_cats/app/views/cats/new.html.erb
<h1> Create a Cat </h1>

<%= render 'form', cat: @cat, type: :new %>

ninety_nine_cats/app/views/cats/show.html.erb
<h1> <%= @cat.name  %> </h1>

<table>
  <tr>
    <th>Attribute</th>
    <th>Value</th>
  </tr>
  <tr>
    <td>Age</td>
    <td><%= @cat.age  %></td>
  </tr>
  <tr>
    <td>Birthday</td>
    <td><%= @cat.birth_date  %></td>
  </tr>
    <tr>
    <td>Color</td>
    <td> <%= @cat.color  %> </td>
  </tr>
    <tr>
    <td>Sex</td>
    <td> <%= @cat.sex  %> </td>
  </tr>
    <tr>
    <td>Description</td>
    <td> <%= @cat.description  %></td>
  </tr>
</table>
<br>
<br>
<h1>Rental Requests</h1>
<table>
  <tr>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Status</>
  </tr>
  <% @cat.cat_rental_requests.order('start_date').each do |rental_request| %>
  <tr> 
    <td> <%= rental_request.start_date %> </td>
    <td> <%= rental_request.end_date  %> </td>
    <td> <%= rental_request.status %> </td>
    <form action="<%= approve_cat_rental_request_url(rental_request) %>" method="post">
      <td> <input type="submit" value="Approve"> </td>
    </form>
    <form action="<%= deny_cat_rental_request_url(rental_request) %>" method="post">
      <td> <input type="submit" value="Deny"> </td>
    </form>
  </tr>
  <% end %>

ninety_nine_cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats99</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>